name: Cryptography

on:
  pull_request:
  push:

jobs:
  test:
    name: Test
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4
      - name: Configure
        run: |
          sudo apt update
          sudo apt install -y libssl-dev openssl valgrind
          sudo gem install ceedling
          chmod +x ceedling
      - name: Build And Test
        run: |
          ./ceedling
        working-directory: ./
      - name: Test Report
        uses: mikepenz/action-junit-report@v4
        with:
          include_passed: true
          report_paths: Build/artifacts/test/junit_tests_report.xml
        if: always()
